# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F4oP1Eh5OLCYB71-AENXCTOt4LAr3fhN
"""

print ("hello word")